extends:
  - stylelint-config-standard
plugins:
  - stylelint-order
rules:
  # use `emptyLineBefore`
  declaration-empty-line-before: null
  order/order:
    - custom-properties
    - declarations
  order/properties-order:
    -
      - content
      -
        groupName: position
        emptyLineBefore: always
        properties:
          - position
          - top
          - right
          - bottom
          - left
          - z-index
      -
        groupName: display
        emptyLineBefore: always
        properties:
          - display
          - align-items
          - justify-content
          - overflow
      -
        groupName: size
        emptyLineBefore: always
        properties:
          - width
          - max-width
          - height
          - max-height
          - margin
          - margin-top
          - margin-right
          - margin-bottom
          - margin-left
          - padding
          - padding-top
          - padding-right
          - padding-bottom
          - padding-left
          - border
          - border-top
          - border-right
          - border-bottom
          - border-left
      -
        groupName: transform
        emptyLineBefore: always
        properties:
          - opacity
          - transform
          - transition
      -
        groupName: font
        emptyLineBefore: always
        properties:
          - color
          - font
          - font-family
          - font-size
          - font-weight
          - text-align
